### ISSUE TITLE
swoole reload 命令对router无效

### ISSUE THREAD

**Issue by fengwuhenyuyousheng** [fastdlabs/fastD#101]
swoole模式下，修改了routes文件，使用reload 命令没有效果，需要stop再start

**Comment by zqhong** [comment]
https://github.com/fastdlabs/swoole/blob/master/src/Server.php#L425-L439

在 reload 方法下重新注册 router 看看。大致类似下面这样。
```php
<?php
unset(app()['router']);
$routeServiceProvider = new \FastD\ServiceProvider\RouteServiceProvider();
app()->register($routeServiceProvider);
```

**Comment by RunnerLee** [comment]
自定义一个 `HTTPServer` 继承 `FastD\Servitization\Server\HTTPServer` 并重写 `reload()` 或是 `onWorkerStart()` 应该就可以的.

**Comment by JanHuang** [comment]
目前已经添加对swoole reload的支持。
