### ISSUE TITLE
关于 raw 数据的获取

### ISSUE THREAD

**Issue by marlonfan** [fastdlabs/fastD#112]
最近在用``dobee``开发一些功能,发现通过``$request->getParsedBody()``方法拿不到``Content-Type:application/json``提交过来的数据.

建议在这种情况下是否可以将``raw``中的数据直接复制给``$_POST``获取参数?

另外提交pr的话是提交到这个仓库么? 还是提交至组件由你来更新项目依赖

**Comment by JanHuang** [comment]
如果是pr的话可以提交到对应的组件，如果是通过getParseBody获取不到的话，可以通过 $request->getBody(); 来获取对应的内容。另外感谢支持使用本项目进行开发。

**Comment by marlonfan** [comment]
非常感谢,另外有一个问题. 现在如果开项目,是使用``fastD``还是使用``DoBee``？ 后期``FastD``骨架还会维护么?

**Comment by JanHuang** [comment]
dobee 是fastd的骨架，fastd是整体的核心，建议使用dobee，这样不用自己手动建立对应文件夹。另外FastD会一直维护的。如果有更好的建议或者特性功能，欢迎反馈。

**Comment by marlonfan** [comment]
了解了. Thanks.
