### ISSUE TITLE
文档系列文章404

### ISSUE THREAD

**Issue by cexll** [fastdlabs/fastD#130]
系列文章
FastD 最佳实践一: 构建 API
FastD 最佳实践二: 构建配置中心
FastD 最佳实践三: 构建API网关
FastD 最佳实践四: 构建系统可视化监控
FastD 最佳实践五: 构建ELK日志分析系统
FastD 最佳实践六: 为应用添加调用链监控 Zipkin

这些文章都404了

**Comment by pluveto** [comment]
怀疑作者已经弃坑了
