### ISSUE TITLE
可以与模版引擎结合使用吗？

### ISSUE THREAD

**Issue by unkang** [fastdlabs/fastD#79]
可以与模版引擎结合使用吗？

**Comment by JanHuang** [comment]
@unkang 您好，是支持。我们有提供服务提供器: [twig service provider](https://github.com/janhuang/viewer)
如果你想自定义实现或者使用其他的，可以选择自己编写一个服务提供器，也是非常简单的: [FastD Service Provider](https://fastdlabs.com/#/zh-cn/advanced/3-3-service-provider)

**Comment by JanHuang** [comment]
@unkang 另外我们的实验机器人也是使用利用viewer实现的界面: [“智障”机器人](http://bot.fastdlabs.com/)
