### ISSUE TITLE
english documentation

### ISSUE THREAD

**Issue by mhf-ir** [fastdlabs/fastD#83]
Is there any chance that we can see English documentation ?
After awesome swoole extension many users around the world need to how to use `fastd` or other repositories ?

**Comment by JanHuang** [comment]
@mhf-ir Yes, we are trying to be doing, so stay tuned。

**Comment by JanHuang** [comment]
@mhf-ir Hey guy, Document is ready. At this: http://fastdlabs.com/#/en-us/3.2/readme
