### ISSUE TITLE
无法使用 fastd/routing v3.1.4

### ISSUE THREAD

**Issue by zqhong** [fastdlabs/fastD#86]
## 问题描述
fastd/fastd v3.1.7 的依赖关系中，需要 fastd/middleware：~1.0.0。
fastd/routing v3.1.3 的依赖关系中，需要 fastd/middleware: ~1.0.0。
而 fastd/routing v3.1.4 的依赖关系中，需要 fastd/middleware: ^1.1。

这样，fastd/routing 最高使用版本为 v3.1.3。

## 相关文件
[fastd/fastd v3.1.7 composer.json](https://github.com/fastdlabs/fastD/blob/v3.1.7/composer.json)
[fastd/routing v3.1.3 composer.json](https://github.com/fastdlabs/routing/blob/v3.1.3/composer.json)
[fastd/routing v3.1.4 composer.json](https://github.com/fastdlabs/routing/blob/v3.1.4/composer.json)

**Comment by JanHuang** [comment]
@zqhong 貌似是存在这个问题。我稍等修复一下

**Comment by JanHuang** [comment]
@zqhong 已修复依赖问题
