### ISSUE TITLE
https的文档地址貌似已经打不开了

### ISSUE THREAD

**Issue by DanceSmile** [fastdlabs/fastD#95]

**Comment by JanHuang** [comment]
您说的是哪个地址?因为最近更改了网站内容，证书方面是暂时撤下去了。所以如果是访问 https://fastdlabs.com 的话，需要换成HTTP，最近会修复该问题。

**Comment by DanceSmile** [comment]
恩 就是这个地址

**Comment by JanHuang** [comment]
已经调整了，可能存在缓存，您需要强制刷新一下。
